version: 2.1
executors:
  node:
    docker:
      - image: cimg/node:20.11.0-browsers
    working_directory: ~/ng-project
orbs:
  browser-tools: circleci/browser-tools@1.4.7
  sonarcloud: sonarsource/sonarcloud@2.0.0
jobs:
  install:
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: ng-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: ng-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run: npm run test:ci
      - persist_to_workspace:
          root: .
          paths:
            - ./coverage
  sonar:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - sonarcloud/scan
  build:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run: npm run build
      - run: echo building docker image poc-ci version:$CIRCLE_BRANCH
      - run: echo uploading docker image poc-ci version:$CIRCLE_BRANCH
  lint:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run: npm run lint
  release:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run: echo creating release process
workflows:
  version: 2
  quality:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - sonar:
          requires:
            - test
          context: SonarCloud
      - build:
          requires:
            - test
            - lint
  release:
    jobs:
      - release:
          filters:
            branches:
              only:
                - main
